POST http://localhost:3000/api/feed
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyLCJmaXJzdE5hbWUiOiJWZWdhcyIsImxhc3ROYW1lIjoiUmljbyIsImVtYWlsIjoidmVnYXNAdmVnYXMuY29tIiwicm9sZSI6InVzZXIifSwiaWF0IjoxNjcwODczMzQ3LCJleHAiOjE2NzA4NzY5NDd9.EaD2aBOBQOrya-ecelJi6j6VHD98cGLxHVGRtfhPJiw

{
    "body": "This is the new post number 1!"
}


### Get all posts
GET http://localhost:3000/api/feed

### Update post
PUT http://localhost:3000/api/feed/2
Content-Type: application/json

{
    "body": "Updated post"
}

### Delete post
DELETE http://localhost:3000/api/feed/2