### Register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "email": "vegas1@vegas.com",
    "password": "123456",
    "lastName": "Rico",
    "firstName": "Vegas"
}

### Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "vegas1@vegas.com",
    "password": "123456"
}