### Register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "email": "vegas1@vegas.com",
    "password": "123456",
    "lastName": "Rico",
    "firstName": "Vegas"
}

### Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "vegas1@vegas.com",
    "password": "123456"
}

### Upload Image
POST http://localhost:3000/api/user/upload
Content-Type: image/png
Content-Disposition: form-data; name="file"; filename="hamas.png"
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJmaXJzdE5hbWUiOiJWZWdhcyIsImxhc3ROYW1lIjoiUmljbyIsImVtYWlsIjoidmVnYXMxQHZlZ2FzLmNvbSIsInJvbGUiOiJ1c2VyIn0sImlhdCI6MTY3MjMyMDQ5MCwiZXhwIjoxNjcyMzI0MDkwfQ.5K-hpow2leCdCCoNOfW6Ut5YYl_e6eXGFZEMHxfiN3A

 < /home/vegas/Pictures/hamas.png
 ------WebKitFormBoundary7MA4YWxkTrZu0gW--

