### Send Friend request
POST http://localhost:3000/api/user/friend-request/send/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyLCJmaXJzdE5hbWUiOiJKb2hubnkiLCJsYXN0TmFtZSI6IlJpY28iLCJlbWFpbCI6ImNvQG1vLnJ1Iiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY3Mzc2MTY5OCwiZXhwIjoxNjczNzY1Mjk4fQ.i2b7j7-hbW9vO0-JupyaaVX7mi8dZOj3Nw0yoeCl0aU


### Check Friend request status
GET http://localhost:3000/api/user/friend-request/status/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjozLCJmaXJzdE5hbWUiOiLQltC10LrQsCIsImxhc3ROYW1lIjoi0KDRi9C60L7QsiIsImVtYWlsIjoiYXNkQGFzZC5ydSIsInJvbGUiOiJ1c2VyIn0sImlhdCI6MTY3Mzc2NjA5MCwiZXhwIjoxNjczNzY5NjkwfQ.TeG0IXk0fsJkJEd1fQmdAD1a_Tqm6SiOQGf_ddaky4o


### Respond Friend request status
PUT http://localhost:3000/api/user/friend-request/response/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjozLCJmaXJzdE5hbWUiOiLQltC10LrQsCIsImxhc3ROYW1lIjoi0KDRi9C60L7QsiIsImVtYWlsIjoiYXNkQGFzZC5ydSIsInJvbGUiOiJ1c2VyIn0sImlhdCI6MTY3Mzc2NjA5MCwiZXhwIjoxNjczNzY5NjkwfQ.TeG0IXk0fsJkJEd1fQmdAD1a_Tqm6SiOQGf_ddaky4o
Content-Type: application/json

{
    "status": "declined"
}

### List of Friend requests t me
GET http://localhost:3000/api/user/friend-request/me/received-requests
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjozLCJmaXJzdE5hbWUiOiLQltC10LrQsCIsImxhc3ROYW1lIjoi0KDRi9C60L7QsiIsImVtYWlsIjoiYXNkQGFzZC5ydSIsInJvbGUiOiJ1c2VyIn0sImlhdCI6MTY3Mzc2NjA5MCwiZXhwIjoxNjczNzY5NjkwfQ.TeG0IXk0fsJkJEd1fQmdAD1a_Tqm6SiOQGf_ddaky4o
