### Send Friend request
POST http://localhost:3000/api/user/friend-request/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJmaXJzdE5hbWUiOiJWZWdhcyIsImxhc3ROYW1lIjoiUmljbyIsImVtYWlsIjoidmVnYXMxQHZlZ2FzLmNvbSIsInJvbGUiOiJ1c2VyIn0sImlhdCI6MTY3MjMyMDQ5MCwiZXhwIjoxNjcyMzI0MDkwfQ.5K-hpow2leCdCCoNOfW6Ut5YYl_e6eXGFZEMHxfiN3A
